# This file was generated by GoReleaser. DO NOT EDIT.
cask "uaanime" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "uaanime"],
          chdir: ".",
          writable_paths: ["uaanime"],
          must_succeed: false
    end
  end

  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "5df36128f95469e3560f1670844325a6b71d9ebc638a4a1d7283bf0d4f899758"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "54c24555eced9444c24aefeb54122dc1607766948e431c11d13851cb057ede31"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa87a039ae84be4b1a90858fba9b6a56c8c7868bdb1e00925b9db89ddc8b087a"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "43938b1a0bd9febc5c89011b9ed2c927c71028e8da1c21164157937760b6b8a5"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_linux_amd64.tar.gz"
    end
  end

  name "uaanime"
  desc "Дивись аніме українською з термінала"
  homepage "https://github.com/Basmanjacks/uaanime"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uaanime"

  # No zap stanza required

  caveats <<~EOS
    Для відтворення потрібен VLC або mpv.
    macOS: brew install --cask vlc (або brew install mpv)
    Linux: постав VLC чи mpv пакетним менеджером системи.
    Перевірка: uaanime doctor
  EOS
end
