# This file was generated by GoReleaser. DO NOT EDIT.
cask "uaanime" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "33d98352573bdb47587b2efa3ca573eebdab48e9e8d963f8432fbda08797b6e2"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c010fb6ad7513bab351151bc234e3dc7718c9ffec93609057a64b900e8cfce2b"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1342113167fc9e5f0a0dafb5b2c12b0f1807683e258d717a9285a3dd0a3ecff8"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2437fae4b942b976ecbb56089deab2ff841b84d371ec14f18119da760a099fcc"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_linux_amd64.tar.gz"
    end
  end

  name "uaanime"
  desc "Дивись аніме українською з термінала"
  homepage "https://github.com/Basmanjacks/uaanime"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "uaanime"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uaanime"]
    end
  end

  # No zap stanza required
end
