# This file was generated by GoReleaser. DO NOT EDIT.
cask "uaanime" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "uaanime"],
          chdir: ".",
          writable_paths: ["uaanime"],
          must_succeed: false
    end
  end

  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "0acf68eeb739bf8dc55c485383efe1a30979e103d37ccc08aa8ea22077f27026"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "72f1050654a34dae976e1c8e37376333ca32d94d4f7ee5a5ee215188bf70c5ed"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "26a06f204c98c7703002524cfa0cbe22b981e6195ca97298e340a39e323b856a"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e47a7f1e6b6a44154e96591848eeaab679e45ead6d1cde054800ef3c1f3bd9f5"
      url "https://github.com/Basmanjacks/uaanime/releases/download/v#{version}/uaanime_linux_amd64.tar.gz"
    end
  end

  name "uaanime"
  desc "Дивись аніме українською з термінала"
  homepage "https://github.com/Basmanjacks/uaanime"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uaanime"

  # No zap stanza required

  caveats <<~EOS
    Для відтворення потрібен VLC або mpv.
    macOS: brew install --cask vlc (або brew install mpv)
    Linux: постав VLC чи mpv пакетним менеджером системи.
    Перевірка: uaanime doctor
  EOS
end
