# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uaanime < Formula
  desc "Дивись аніме українською з термінала"
  homepage "https://github.com/Basmanjacks/uaanime"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.2.0/uaanime_darwin_amd64.tar.gz"
      sha256 "789b7bbb4876e097177799a46d537cabcec9759e0faae52b4f50dc70931da771"

      define_method(:install) do
        bin.install "uaanime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.2.0/uaanime_darwin_arm64.tar.gz"
      sha256 "ff70d269170822cdfd0fa09a247d26ee0553d6bf2dc6d049918ff00cfb8d1f61"

      define_method(:install) do
        bin.install "uaanime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.2.0/uaanime_linux_amd64.tar.gz"
      sha256 "3bb894dfa5d3805d1a6bbe72ad2462358dd8f06380277e75b74de25382d19dbc"
      define_method(:install) do
        bin.install "uaanime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.2.0/uaanime_linux_arm64.tar.gz"
      sha256 "13c442068872f4eddf595935f8fd28919c88d2fcde5252eb43d4cf87d8130359"
      define_method(:install) do
        bin.install "uaanime"
      end
    end
  end
end
