# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uaanime < Formula
  desc "Дивись аніме українською з термінала"
  homepage "https://github.com/Basmanjacks/uaanime"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.3.0/uaanime_darwin_amd64.tar.gz"
      sha256 "3896aefe22f6d7cfc327f9f871b326a842a679d47feda207dae8e4902344de12"

      define_method(:install) do
        bin.install "uaanime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.3.0/uaanime_darwin_arm64.tar.gz"
      sha256 "00d91491aa9c250376c3c0add61dafedb636fb9619bc2ea4396a0b6cf27aed56"

      define_method(:install) do
        bin.install "uaanime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.3.0/uaanime_linux_amd64.tar.gz"
      sha256 "e39987891e1b1b1e516c013af6716e6a7d32d88247e36457a54ccd2aebd4ced7"
      define_method(:install) do
        bin.install "uaanime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.3.0/uaanime_linux_arm64.tar.gz"
      sha256 "812389251290d9f5c763b4bbb2dd96f0fa8dcd5c996b5b075dfbce67e86209f0"
      define_method(:install) do
        bin.install "uaanime"
      end
    end
  end

  def caveats
    <<~EOS
      Для відтворення потрібен VLC або mpv.
      Встанови один із них пакетним менеджером системи.
      Перевірка: uaanime doctor
    EOS
  end
end
