# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uaanime < Formula
  desc "Дивись аніме українською з термінала"
  homepage "https://github.com/Basmanjacks/uaanime"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.5.0/uaanime_darwin_amd64.tar.gz"
      sha256 "f61be3dbade4b08db987e35ee93d7cd27e64cb4210828dea59af744d54754233"

      define_method(:install) do
        bin.install "uaanime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.5.0/uaanime_darwin_arm64.tar.gz"
      sha256 "868e45fd855d89ffc90250ba450e9393f8aa3e63b1b6c77cca0dd6521b7225db"

      define_method(:install) do
        bin.install "uaanime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.5.0/uaanime_linux_amd64.tar.gz"
      sha256 "340571b474d0bd10d69db556ae622da9c78b246d42010b576821c391ac2794bf"
      define_method(:install) do
        bin.install "uaanime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basmanjacks/uaanime/releases/download/v0.5.0/uaanime_linux_arm64.tar.gz"
      sha256 "f9e3d2533f1d0eb5427faebd54ddacc561fec34ce1444ea2efc7b6f91496f73e"
      define_method(:install) do
        bin.install "uaanime"
      end
    end
  end

  def caveats
    <<~EOS
      Для відтворення потрібен VLC або mpv.
      Встанови один із них пакетним менеджером системи.
      Перевірка: uaanime doctor
    EOS
  end
end
